// import("tailwindcss").Config;

module.exports = {
  content: [
    "./index.html",
    "./src/App.vue",
    "./src/views/Authentication/userSignIn.vue",
    "./src/views/Authentication/userSignUp.vue",
    "./src/components/TheNavigator/TheHeader.vue",
    "./src/components/TheNavigator/MultiLevelDropdownNav.vue",
    "./src/views/HomePage/HomeView.vue",
    "./src/views/CraftChocolate/CraftChocolateView.vue",
    "./src/views/CraftChocolate/ProductReviewView.vue",
    "./src/components/TheNavigator/cartList.vue",
    "./src/components/TheNavigator/CartBalloon.vue",
    "./src/components/HomeView/CraftChocolateSection.vue",
    "./src/components/UI/BaseProductCardVertical.vue",
    "./src/components/UI/BaseProductCard.vue",
    "./src/components/CraftChocolateView/Carousel.vue",
    "./src/views/Products/ProductTypeListView.vue",
    "./src/components/TheNavigator/TheHeader.vue",
    "./src/components/TheNavigator/Notifications.vue",
    "./src/components/TheNavigator/UserProfile.vue",
    "./node_modules/flowbite/src/dropdown.js",
    "./src/views/Rating/RatingView.vue",
    "./src/components/UI/BaseRatingCard.vue",
    "./src/components/UI/BaseRatingCardHorizontal.vue",
    "./src/components/UI/BaseCommentBox.vue",
    "./src/views/Community/CommunityView.vue",
    "./src/components/CommunityView/ArticleFrame.vue",
    "./src/components/UI/BaseCardNav.vue",
    "./src/components/UI/BaseBtnAddToCart.vue",
    "./src/components/UI/BaseSearchBar.vue",
    "./src/views/Rating/VoteInformation.vue",
    "./src/views/Store/StoreInformation.vue",
    "./src/components/PageNotFound/InDevelopment.vue",
    "./src/components/PageNotFound/NotFoundPage.vue",
    "./src/views/Community/ReadArticle.vue",
    "./src/views/CheckOut/ReviewCartView.vue",
    "./src/components/CheckOut/ItemInCart.vue",
    "./src/views/CheckOut/CodeVoucherView.vue",
    "./src/components/UI/BaseErrorPopUp.vue",
    "./src/views/HomePage/WhoAreGuestPopUp.vue",
    "./src/components/UI/BasePictureFrame.vue",
    "./src/components/ReUseComp/ThePagination.vue",
    "./src/views/Community/SearchByTagName.vue",
    "./src/views/Store/MyStore/myStoreDashboard.vue",
    "./src/views/Store/MyStore/MyStore_dashboard.vue",
    "./src/views/Store/MyStore/MyStore_inventory.vue",
    "./src/views/Store/MyStore/MyStore_orderList.vue",
    "./src/views/Store/MyStore/MyStore_edit_ItemInventory.vue",
    "./src/components/MyStoreView/Dashboard/SummaryCard.vue",
    "./src/components/PopUp/GuestUserAskName.vue",
  ],
  theme: {
    extend: {
      animation: {
        MoveInRight: "MoveInRight 0.6s ease-in-out both",
        scaleUp: "scaleUp 0.4s ease-in-out both",
      },
      keyframes: () => ({
        MoveInRight: {
          "0%": { transform: "translateX(-100px)", opacity: "0" },
          "85%": { transform: "translateX(1.5px)", opacity: "1" },
          "100%": { transform: "translateX(0px)", opacity: "1" },
        },
        scaleUp: {
          "0%": { transform: "scale(0)", opacity: "0" },
          "85%": { transform: "scale(1.03)", opacity: "1" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      }),
    },
  },
  plugins: [require("flowbite/plugin")],
};
